url: www.joeshell.com
baseurl: ''

# Site settings
title: "Michelle and Joe"
email: minuccianirocko@gmail.com
description: "M&J"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3dbbf0
  secondary: 2f90b9  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)


# Build settings
markdown: kramdown
permalink: pretty